# Generated by Django 5.2.1 on 2025-06-02 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='contengt',
            new_name='content',
        ),
    ]
